-- Generated by tools/gen_camp.py — do not edit.
-- Source: https://wago.tools/db2/Spell/csv?build=1.60.1.69977 (the Camp Benefits and Camp Tent
-- auras' descriptions), with SpellEffect, SpellMisc and SpellDuration of the same build for the numbers.
-- None scales with level. { aura, feature, effect, seconds it lasts (none for the tent's rest lockout) }.
local _, ns = ...
ns.CampBenefits = {
	{
		1229451,
		"Tent",
		"Increases Rested Experience after 30 sec spent resting near the tent. You may only gain this benefit once "
			.. "per hour.",
	},
	{ 1230587, "Mana Well", "Restores 29 Mana every 5 seconds", 3600 },
	{ 1230172, "Sharpening Wheel", "Strength increased by 34", 3600 },
	{
		1230653,
		"Enchanted Lute",
		"Armor increased by 308, all attributes increased by 13, and all resistances increased by 22",
		3600,
	},
	{ 1230124, "First Aid Kit", "Stamina increased by 56", 3600 },
	{ 1230098, "Fish Bowl", "All stats increased by 8%", 3600 },
	{ 1229513, "Incense Candle", "Intellect increased by 25", 3600 },
	{ 1230164, "Lodestone", "Melee Attack Power increased by 90", 3600 },
	{ 1229519, "Camp Chair", "Critical strike chance with all spells and attacks increased by 2%", 3600 },
	{ 1229718, "Faction Banner", "Spirit increased by 32", 3600 },
}
