-- Generated by tools/gen_dungeons.py — do not edit.
-- Dungeon and raid entrances by UiMap ID, from Map.Corpse (build 1.60.1.69977). A pin lists its instances
-- (Map IDs); one with an area is a complex of several, named by that AreaTable ID.
local _, ns = ...
ns.DungeonEntrances = {
	[1413] = { -- The Barrens
		{ x = 0.477, y = 0.35, instances = { 43 } }, -- Wailing Caverns
		{ x = 0.423, y = 0.899, instances = { 47 } }, -- Razorfen Kraul
		{ x = 0.509, y = 0.929, instances = { 129 } }, -- Razorfen Downs
	},
	[1414] = { -- Kalimdor
		{ x = 0.443, y = 0.349, instances = { 48 } }, -- Blackfathom Deeps
		{ x = 0.584, y = 0.448, instances = { 389 } }, -- Ragefire Chasm
		{ x = 0.524, y = 0.552, instances = { 43 } }, -- Wailing Caverns
		{ x = 0.384, y = 0.58, instances = { 349 } }, -- Maraudon
		{ x = 0.433, y = 0.681, instances = { 429 } }, -- Dire Maul
		{ x = 0.521, y = 0.708, instances = { 47, 129 } }, -- Razorfen Kraul, Razorfen Downs
		{ x = 0.566, y = 0.715, instances = { 249 } }, -- Onyxia's Lair
		{ x = 0.542, y = 0.799, instances = { 209 } }, -- Zul'Farrak
		{ x = 0.422, y = 0.852, instances = { 509, 531 }, area = 3478 }, -- Gates of Ahn'Qiraj
	},
	[1415] = { -- Eastern Kingdoms
		{ x = 0.551, y = 0.174, instances = { 329 } }, -- Stratholme
		{ x = 0.478, y = 0.195, instances = { 189 } }, -- Scarlet Monastery
		{ x = 0.527, y = 0.264, instances = { 289 } }, -- Scholomance
		{ x = 0.41, y = 0.328, instances = { 33 } }, -- Shadowfang Keep
		{ x = 0.428, y = 0.538, instances = { 90 } }, -- Gnomeregan
		{ x = 0.538, y = 0.576, instances = { 70 } }, -- Uldaman
		{ x = 0.486, y = 0.637, instances = { 229, 230, 409, 469 }, area = 25 }, -- Blackrock Mountain
		{ x = 0.43, y = 0.692, instances = { 34 } }, -- Stormwind Stockade
		{ x = 0.568, y = 0.752, instances = { 109 } }, -- Sunken Temple
		{ x = 0.407, y = 0.796, instances = { 36 } }, -- Deadmines
		{ x = 0.489, y = 0.826, instances = { 309 } }, -- Zul'Gurub
	},
	[1418] = { -- Badlands
		{ x = 0.352, y = 0.103, instances = { 70 } }, -- Uldaman
	},
	[1420] = { -- Tirisfal Glades
		{ x = 0.851, y = 0.314, instances = { 189 } }, -- Scarlet Monastery
	},
	[1421] = { -- Silverpine Forest
		{ x = 0.447, y = 0.678, instances = { 33 } }, -- Shadowfang Keep
	},
	[1422] = { -- Western Plaguelands
		{ x = 0.691, y = 0.73, instances = { 289 } }, -- Scholomance
	},
	[1423] = { -- Eastern Plaguelands
		{ x = 0.261, y = 0.104, instances = { 329 } }, -- Stratholme
	},
	[1426] = { -- Dun Morogh
		{ x = 0.177, y = 0.392, instances = { 90 } }, -- Gnomeregan
	},
	[1427] = { -- Searing Gorge
		{ x = 0.333, y = 0.876, instances = { 229, 230, 409 }, area = 25 }, -- Blackrock Mountain
	},
	[1428] = { -- Burning Steppes
		{ x = 0.286, y = 0.224, instances = { 229, 230, 409, 469 }, area = 25 }, -- Blackrock Mountain
	},
	[1434] = { -- Stranglethorn Vale
		{ x = 0.54, y = 0.176, instances = { 309 } }, -- Zul'Gurub
	},
	[1435] = { -- Swamp of Sorrows
		{ x = 0.773, y = 0.359, instances = { 109 } }, -- Sunken Temple
	},
	[1436] = { -- Westfall
		{ x = 0.382, y = 0.775, instances = { 36 } }, -- Deadmines
	},
	[1440] = { -- Ashenvale
		{ x = 0.165, y = 0.11, instances = { 48 } }, -- Blackfathom Deeps
	},
	[1443] = { -- Desolace
		{ x = 0.291, y = 0.629, instances = { 349 } }, -- Maraudon
	},
	[1444] = { -- Feralas
		{ x = 0.62, y = 0.333, instances = { 429 } }, -- Dire Maul
	},
	[1445] = { -- Dustwallow Marsh
		{ x = 0.529, y = 0.777, instances = { 249 } }, -- Onyxia's Lair
	},
	[1446] = { -- Tanaris
		{ x = 0.387, y = 0.199, instances = { 209 } }, -- Zul'Farrak
	},
	[1451] = { -- Silithus
		{ x = 0.29, y = 0.927, instances = { 509, 531 }, area = 3478 }, -- Gates of Ahn'Qiraj
	},
	[1453] = { -- Stormwind City
		{ x = 0.504, y = 0.662, instances = { 34 } }, -- Stormwind Stockade
	},
	[1454] = { -- Orgrimmar
		{ x = 0.53, y = 0.489, instances = { 389 } }, -- Ragefire Chasm
	},
}
ns.RaidInstances = {
	[249] = true, -- Onyxia's Lair
	[309] = true, -- Zul'Gurub
	[409] = true, -- Molten Core
	[469] = true, -- Blackwing Lair
	[509] = true, -- Ruins of Ahn'Qiraj
	[531] = true, -- Ahn'Qiraj Temple
}
