-- Generated by tools/gen_zonelevels.py — do not edit.
-- Level ranges by UiMap ID. The original game's zones take its published range:
-- https://warcraft.wiki.gg/wiki/Zones_by_level_(original)
-- Forever's own zones take the lowest and highest exploration level of their subzones
-- (AreaTable.ExplorationLevel, build 1.60.1.69977). C_Map.GetMapLevels wins wherever it returns a range.
local _, ns = ...
ns.ZoneRanges = {
	[1411] = { 1, 10 }, -- Durotar
	[1412] = { 1, 10 }, -- Mulgore
	[1413] = { 10, 25 }, -- The Barrens
	[1416] = { 30, 40 }, -- Alterac Mountains
	[1417] = { 30, 40 }, -- Arathi Highlands
	[1418] = { 35, 45 }, -- Badlands
	[1419] = { 45, 55 }, -- Blasted Lands
	[1420] = { 1, 10 }, -- Tirisfal Glades
	[1421] = { 10, 20 }, -- Silverpine Forest
	[1422] = { 51, 58 }, -- Western Plaguelands
	[1423] = { 53, 60 }, -- Eastern Plaguelands
	[1424] = { 20, 30 }, -- Hillsbrad Foothills
	[1425] = { 40, 50 }, -- The Hinterlands
	[1426] = { 1, 10 }, -- Dun Morogh
	[1427] = { 45, 50 }, -- Searing Gorge
	[1428] = { 50, 58 }, -- Burning Steppes
	[1429] = { 1, 10 }, -- Elwynn Forest
	[1430] = { 55, 60 }, -- Deadwind Pass
	[1431] = { 18, 30 }, -- Duskwood
	[1432] = { 10, 20 }, -- Loch Modan
	[1433] = { 15, 25 }, -- Redridge Mountains
	[1434] = { 30, 45 }, -- Stranglethorn Vale
	[1435] = { 35, 45 }, -- Swamp of Sorrows
	[1436] = { 10, 20 }, -- Westfall
	[1437] = { 20, 30 }, -- Wetlands
	[1438] = { 1, 10 }, -- Teldrassil
	[1439] = { 10, 20 }, -- Darkshore
	[1440] = { 18, 30 }, -- Ashenvale
	[1441] = { 25, 35 }, -- Thousand Needles
	[1442] = { 15, 27 }, -- Stonetalon Mountains
	[1443] = { 30, 40 }, -- Desolace
	[1444] = { 40, 50 }, -- Feralas
	[1445] = { 35, 45 }, -- Dustwallow Marsh
	[1446] = { 40, 50 }, -- Tanaris
	[1447] = { 45, 55 }, -- Azshara
	[1448] = { 48, 55 }, -- Felwood
	[1449] = { 48, 55 }, -- Un'Goro Crater
	[1450] = { 55, 60 }, -- Moonglade
	[1451] = { 55, 60 }, -- Silithus
	[1452] = { 53, 60 }, -- Winterspring
	[2521] = { 3, 12 }, -- Zephras Isle (exploration levels)
	[2548] = { 36, 44 }, -- Riverglades (exploration levels)
}
