"""Generate the explicit Forever quest IDs from pinned QuestV2 CSVs (wago.tools).

Usage: python3 tools/gen_foreverquests.py FOREVER.csv ERA.csv
Sources: https://wago.tools/db2/QuestV2/csv?build=1.60.1.69913
         https://wago.tools/db2/QuestV2/csv?build=1.15.9.69722
An unknown ID is deliberately unmarked; regenerate when the client data changes.
"""

import csv
import sys
from pathlib import Path


def ids(path):
    with Path(path).open(encoding="utf-8-sig", newline="") as source:
        return {int(row["ID"]) for row in csv.DictReader(source)}


def render(quests):
    return "\n".join(
        [
            "-- Generated by tools/gen_foreverquests.py; do not edit.",
            "-- QuestV2: 1.60.1.69913 (Forever) minus 1.15.9.69722 (Classic Era), from wago.tools.",
            "---@type string, TFNamespace",
            "local _, ns = ...",
            "ns.ForeverQuests = {",
            *[f"\t[{quest}] = true," for quest in sorted(quests)],
            "}",
            "",
        ]
    )


if __name__ == "__main__":
    output = Path(__file__).resolve().parent.parent / "Data" / "ForeverQuests.lua"
    output.write_text(render(ids(sys.argv[1]) - ids(sys.argv[2])))
