#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Generate lazy map-art overlay data for the pinned Forever client (stdlib only)."""

import argparse
import sys
import urllib.error
from collections import defaultdict
from pathlib import Path

try:
    from tools.forever_tools import wago
    from tools.forever_tools.fsio import atomic_write
except ModuleNotFoundError:
    from forever_tools import wago
    from forever_tools.fsio import atomic_write

BUILD = "1.60.1.70235"
ROOT = Path(__file__).resolve().parent.parent
USER_AGENT = "TweaksForever/1.0"
CACHE = ROOT / "tools" / ".cache"
OUTPUT = ROOT / "Data" / "Overlays.lua"
SCHEMAS = {
    "WorldMapOverlay": ("UiMapArtID", "OffsetX", "OffsetY", "TextureWidth", "TextureHeight", "PlayerConditionID"),
    "WorldMapOverlayTile": ("WorldMapOverlayID", "LayerIndex", "RowIndex", "ColIndex", "FileDataID"),
    "UiMapArt": ("UiMapArtStyleID",),
    "UiMapArtStyleLayer": ("UiMapArtStyleID", "LayerIndex", "TileWidth", "TileHeight"),
}


def db2(name, refresh=False, offline=False):
    columns = ("ID", *SCHEMAS[name])
    rows = {}
    for row in wago.db2_rows(
        name, BUILD, CACHE, user_agent=USER_AGENT, refresh=refresh, offline=offline, ints=columns, required=columns
    ):
        if int(row["ID"]) <= 0:
            raise ValueError(f"{name}: invalid ID {row['ID']}")
        rows[row["ID"]] = {key: row[key] for key in columns}
    return rows


def generate(tables):
    overlays, arts = tables["WorldMapOverlay"], tables["UiMapArt"]
    layers = {}
    for row in tables["UiMapArtStyleLayer"].values():
        key = row["UiMapArtStyleID"], row["LayerIndex"]
        if key in layers or min(row["TileWidth"], row["TileHeight"]) <= 0:
            raise ValueError(f"Invalid/duplicate art layer: {key}")
        layers[key] = row
    tiles = defaultdict(dict)
    for row in tables["WorldMapOverlayTile"].values():
        oid = row["WorldMapOverlayID"]
        if oid not in overlays:
            raise ValueError(f"Orphan tile: {row['ID']}")
        key = row["LayerIndex"], row["RowIndex"], row["ColIndex"]
        if key in tiles[oid] or min(key) < 0 or row["FileDataID"] <= 0:
            raise ValueError(f"Overlay {oid}: invalid/duplicate tile {key}")
        tiles[oid][key] = row["FileDataID"]

    packed, seen = defaultdict(list), set()
    missing, count = 0, 0
    for oid, row in sorted(overlays.items()):
        art = row["UiMapArtID"]
        if art not in arts:
            raise ValueError(f"Overlay {oid}: missing art {art}")
        if row["PlayerConditionID"]:
            raise ValueError(f"Overlay {oid}: player condition needs runtime support")
        source = tiles[oid]
        if not source:
            missing += 1
            continue
        rect = tuple(row[key] for key in ("OffsetX", "OffsetY", "TextureWidth", "TextureHeight"))
        x, y, width, height = rect
        if min(x, y) < 0 or min(width, height) <= 0:
            raise ValueError(f"Overlay {oid}: invalid rectangle")
        for index in sorted({key[0] for key in source}):
            layer = layers[arts[art]["UiMapArtStyleID"], index]
            wide = (width + layer["TileWidth"] - 1) // layer["TileWidth"]
            tall = (height + layer["TileHeight"] - 1) // layer["TileHeight"]
            expected = {(index, r, c) for r in range(tall) for c in range(wide)}
            actual = {key for key in source if key[0] == index}
            if expected != actual:
                raise ValueError(f"Overlay {oid}: incomplete/out-of-grid layer {index}")
            key = art, index, rect
            if key in seen:
                raise ValueError(f"Overlay {oid}: duplicate rectangle on art/layer {art}/{index}")
            seen.add(key)
            files = [source[index, r, c] for r in range(tall) for c in range(wide)]
            # One record per overlay/layer; indices match the canvas's one-based layers.
            packed[art].append(",".join(map(str, (index + 1, *rect, *files))) + ";")
            count += 1

    lines = [
        "-- Generated by tools/gen_overlays.py — do not edit.",
        f"-- Source: https://wago.tools/db2/WorldMapOverlay/csv?build={BUILD}",
        f"-- WorldMapOverlayTile, UiMapArt, UiMapArtStyleLayer: same source/build {BUILD}.",
        "-- Per art: layer,x,y,width,height,fileDataIDs (row-major); decoded only for the viewed map.",
        "local _, ns = ...",
        "ns.Overlays = {",
    ]
    for art, records in sorted(packed.items()):
        text = "".join(records)
        chunks = [text[i : i + 100] for i in range(0, len(text), 100)]
        lines.append(f"\t[{art}] = " + f'"{chunks[0]}"' + ("," if len(chunks) == 1 else ""))
        lines.extend(
            f'\t\t.. "{chunk}"' + ("," if i == len(chunks) - 1 else "") for i, chunk in enumerate(chunks[1:], 1)
        )
    lines.extend(("}", ""))
    return "\n".join(lines).encode(), len(packed), count, missing


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--refresh", action="store_true", help="Download the pinned CSVs again")
    group.add_argument("--offline", action="store_true", help="Require cached CSVs")
    args = parser.parse_args()
    tables = {name: db2(name, **vars(args)) for name in SCHEMAS}
    data, arts, count, missing = generate(tables)
    atomic_write(OUTPUT, data)
    print(f"{OUTPUT}: {len(data):,} bytes, {arts} map arts, {count} overlays; {missing} tile-less rows omitted")


if __name__ == "__main__":
    try:
        main()
    except (ValueError, KeyError, OSError, urllib.error.URLError) as error:
        sys.exit(f"gen_overlays: {error}")
