"""Generate the explicit Forever quest IDs from pinned QuestV2 CSVs (wago.tools).

Usage: python3 tools/gen_foreverquests.py [--offline | --refresh]
       python3 tools/gen_foreverquests.py FOREVER.csv ERA.csv
Sources: https://wago.tools/db2/QuestV2/csv for builds BUILD (Forever) and ERA_BUILD (Classic Era)
An unknown ID is deliberately unmarked; regenerate when the client data changes.
"""

import argparse
from pathlib import Path

from forever_tools import csvtable
from forever_tools.fsio import atomic_write
from gen_classspells import db2

BUILD = "1.60.1.70245"
ERA_BUILD = "1.15.9.69722"


def ids(path):
    rows = csvtable.parse_csv(Path(path).read_text(encoding="utf-8-sig"), str(path), ints=["ID"])
    return {row["ID"] for row in rows}


def render(quests):
    return "\n".join(
        [
            "-- Generated by tools/gen_foreverquests.py; do not edit.",
            f"-- QuestV2: {BUILD} (Forever) minus {ERA_BUILD} (Classic Era), from wago.tools.",
            "---@type string, TFNamespace",
            "local _, ns = ...",
            "ns.ForeverQuests = {",
            *[f"\t[{quest}] = true," for quest in sorted(quests)],
            "}",
            "",
        ]
    )


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("forever", nargs="?")
    parser.add_argument("era", nargs="?")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--offline", action="store_true")
    mode.add_argument("--refresh", action="store_true")
    args = parser.parse_args()
    if bool(args.forever) != bool(args.era):
        parser.error("provide both CSV paths, or neither to fetch the pinned builds")
    if args.forever:
        quests = ids(args.forever) - ids(args.era)
    else:
        forever, era = (
            {int(row["ID"]) for row in db2("QuestV2", build, offline=args.offline, refresh=args.refresh)}
            for build in (BUILD, ERA_BUILD)
        )
        quests = forever - era
    output = Path(__file__).resolve().parent.parent / "Data" / "ForeverQuests.lua"
    atomic_write(output, render(quests))


if __name__ == "__main__":
    main()
